### ISSUE TITLE
Kuhn poker game description

### ISSUE THREAD

**Issue by mervai** [lab-ml/poker#2]
Hi amazing work!

I noticed a discrepancy between your description of Kuhn poker and [Wikepedia's version](https://en.wikipedia.org/wiki/Kuhn_poker#Game_description).

In your vesion, once player 1 (assuming first to act) checks, player 2 does not get a chance to bet. Whereas, on Wikepedia the second player has the option to bet or check. I'm not sure if there are different versions of kuhn poker but I thought this was an interesting observation. 

I am quite a fan of how you've used typing and vectorization by the way, I'm hoping to learn from this repository.

**Comment by vpj** [comment]
The Wikipedia version is probably the correct one. I may have picked up a simpler version of Kuhn Poker I heard on a video lecture and read on a tutorial.

Thanks
